version: "3.8"
services:
  order-up-db:
    build: ./db/
    image: order-up-db:1.0
    container_name: order-up-db
    init: true
    restart: always
    # ports are used internally only so needn't be cited here
  order-up-app :
    build: ./app/
    image: order-up-app:1.0
    container_name: order-up-app
    init: true
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - order-up-db

