# generated this by deploying a multi-container service via the web UI
# and then copying the YAML it produced from the running service
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: order-up-app
  generation: 2
  labels:
    cloud.googleapis.com/location: us-east5
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/container-dependencies: '{"order-up-app":["order-up-db"]}'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - name: order-up-app
          image: us-east5-docker.pkg.dev/wolvctf-2024/locker/order-up-app:1.0
          ports:
            - name: http1
              containerPort: 5000
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 5000
        - name: order-up-db
          image: us-east5-docker.pkg.dev/wolvctf-2024/locker/order-up-db:1.0
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            timeoutSeconds: 200
            periodSeconds: 200
            failureThreshold: 3
            tcpSocket:
              port: 5432
