apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  generation: 2
  labels:
    cloud.googleapis.com/location: us-east5
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/minScale: '1'
  name: limited-app
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/container-dependencies: '{"limited-app":["limited-db"]}'
    spec:
      containerConcurrency: 20
      timeoutSeconds: 300
      containers:
        - name: limited-app
          image: "${GCLOUD_TAG2}"
          ports:
            - name: http1
              containerPort: 8000
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8000
        - name: limited-db
          image: "${GCLOUD_TAG1}"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            timeoutSeconds: 200
            periodSeconds: 200
            failureThreshold: 3
            tcpSocket:
              port: 3306
